Этот рабочий процесс будет запускать тесты с использованием node, а затем публиковать пакет в пакетах GitHub при создании выпуска
# Для получения дополнительной информации смотрите: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

имя: discord.js шаблон бота

вкл:
  освободить:
    типы: [создано]

Вакансии:
  строить:
    запущенный: ubuntu-последняя версия
    шаги:
 - использует: действия/оформитьзаказ@v2
 - использование: действия/настройка-node@v1
        с:
          версия узла: 12
 - запуск: npm ci
 - выполнить: тест npm

  опубликовать-npm:
    потребности: построить
    запущенный: ubuntu-последняя версия
    шаги:
 - использует: действия/оформитьзаказ@v2
 - использование: действия/настройка-node@v1
        с:
          версия узла: 12
          реестр-url:https://registry.npmjs.org/
 - запуск: npm ci
 - выполнить: опубликовать npm
        зав:
          NODE_AUTH_TOKEN: ${{секреты.npm_token}}

  публикация-георадар:
    потребности: построить
    запущенный: ubuntu-последняя версия
    шаги:
 - использует: действия/оформитьзаказ@v2
 - использование: действия/настройка-node@v1
        с:
          версия узла: 12
          реестр-url:https://npm.pkg.github.com/
 - запуск: npm ci
 - выполнить: опубликовать npm
        зав:
          NODE_AUTH_TOKEN: ${{секреты.GITHUB_TOKEN}}
